In [5]:
import pandas as pd
import os

In [6]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
os.getcwd()

'/Users/dhanaprakashdurairaj/Documents/GitHub/nba-player-analytics/Pre-processing/preprocessing_data'

In [8]:
# File to Load (Remember to change these)
player_stats_201617_data_to_load = "../../Resources/NBA Players Stats 201617.csv"
player_stats_201718_data_to_load = "../../Resources/NBA Players Stats 201718.csv"
player_stats_201819_data_to_load = "../../Resources/NBA Players Stats 201819.csv"
player_stats_201920_data_to_load = "../../Resources/NBA STATs19-20.csv"

player_salary_2019_to_present_data_to_load = "../../Resources/NBA_salaries_2019_present.csv"
player_salary_2016_to_2019_data_to_load = "../../Resources/nba_stats_salaries_16-19.csv"

print(player_stats_201617_data_to_load)
print(player_stats_201718_data_to_load)
print(player_stats_201819_data_to_load)
print(player_stats_201920_data_to_load)

print(player_salary_2016_to_2019_data_to_load)
print(player_salary_2019_to_present_data_to_load)

../../Resources/NBA Players Stats 201617.csv
../../Resources/NBA Players Stats 201718.csv
../../Resources/NBA Players Stats 201819.csv
../../Resources/NBA STATs19-20.csv
../../Resources/nba_stats_salaries_16-19.csv
../../Resources/NBA_salaries_2019_present.csv

In [9]:
print(os.path.isfile(player_stats_201617_data_to_load))
print(os.path.isfile(player_stats_201718_data_to_load))
print(os.path.isfile(player_stats_201819_data_to_load))
print(os.path.isfile(player_stats_201920_data_to_load))

print(os.path.isfile(player_salary_2016_to_2019_data_to_load))
print(os.path.isfile(player_salary_2019_to_present_data_to_load))

True
True
True
True
True
True

In [10]:
# Read the Player Stat and Salary Data
player_stats_201617_df = pd.read_csv(player_stats_201617_data_to_load)
player_stats_201718_df = pd.read_csv(player_stats_201718_data_to_load)
player_stats_201819_df = pd.read_csv(player_stats_201819_data_to_load)
player_stats_201920_df = pd.read_csv(player_stats_201920_data_to_load)

player_salary_2016_to_2019_df = pd.read_csv(player_salary_2016_to_2019_data_to_load)
player_salary_2019_to_present_df = pd.read_csv(player_salary_2019_to_present_data_to_load)

dataframe_analyzed_df = player_stats_201819_df

In [11]:
dataframe_analyzed_df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,√Ålex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,0.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,0.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,0.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,0.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,0.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,528,Tyler Zeller\zellety01,C,29,MEM,4,1,20.5,4.0,7.0,...,0.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
704,529,Ante ≈Ωi≈æiƒá\zizican01,C,22,CLE,59,25,18.3,3.1,5.6,...,0.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
705,530,Ivica Zubac\zubaciv01,C,21,TOT,59,37,17.6,3.6,6.4,...,0.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
706,530,Ivica Zubac\zubaciv01,C,21,LAL,33,12,15.6,3.4,5.8,...,0.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
707,530,Ivica Zubac\zubaciv01,C,21,LAC,26,25,20.2,3.8,7.2,...,0.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

In [12]:
dataframe_analyzed_df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,√Ålex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,0.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,0.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,0.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,0.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,0.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [13]:
dataframe_analyzed_df.count()

Rk        708
Player    708
Pos       708
Age       708
Tm        708
G         708
GS        708
MP        708
FG        708
FGA       708
FG%       702
3P        708
3PA       708
3P%       661
2P        708
2PA       708
2P%       693
eFG%      702
FT        708
FTA       708
FT%       665
ORB       708
DRB       708
TRB       708
AST       708
STL       708
BLK       708
TOV       708
PF        708
PTS       708
dtype: int64

In [14]:
dataframe_analyzed_df.isnull().sum()

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        6
3P         0
3PA        0
3P%       47
2P         0
2PA        0
2P%       15
eFG%       6
FT         0
FTA        0
FT%       43
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
dtype: int64

In [15]:
dataframe_analyzed_df.describe()

,Rk,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
count,708.000000,708.000000,708.000000,708.000000,708.000000,708.000000,708.000000,702.000000,708.000000,708.000000,...,665.000000,708.000000,708.000000,708.000000,708.000000,708.000000,708.000000,708.000000,708.000000,708.000000
mean,268.357345,26.142655,42.882768,19.847458,19.265254,3.091949,6.885028,0.437301,0.884181,2.558898,...,0.739629,0.821610,2.738701,3.557345,1.834605,0.609746,0.370339,1.033475,1.724859,8.384322
std,150.783267,4.141178,26.282043,25.858704,9.023905,2.116415,4.396151,0.109997,0.788803,2.059268,...,0.143505,0.771119,1.870375,2.488335,1.642428,0.420888,0.387384,0.748687,0.812302,5.828200
min,1.000000,19.000000,1.000000,0.000000,0.700000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,137.750000,23.000000,19.000000,0.000000,12.200000,1.500000,3.500000,0.400000,0.300000,0.900000,...,0.684000,0.300000,1.475000,1.800000,0.800000,0.300000,0.100000,0.500000,1.200000,4.000000
50%,269.500000,26.000000,44.000000,6.000000,19.100000,2.600000,6.000000,0.434000,0.800000,2.200000,...,0.763000,0.600000,2.300000,3.000000,1.300000,0.500000,0.300000,0.900000,1.700000,7.000000
75%,398.250000,29.000000,68.000000,32.000000,27.100000,4.200000,9.400000,0.485000,1.300000,3.800000,...,0.825000,1.100000,3.600000,4.625000,2.400000,0.800000,0.500000,1.400000,2.300000,11.500000
max,530.000000,42.000000,82.000000,82.000000,36.900000,10.800000,24.500000,1.000000,5.100000,13.200000,...,1.000000,5.400000,11.100000,15.600000,10.700000,2.400000,2.700000,5.000000,4.000000,36.100000

In [16]:
dataframe_analyzed_df.dtypes

Rk          int64
Player     object
Pos        object
Age         int64
Tm         object
G           int64
GS          int64
MP        float64
FG        float64
FGA       float64
FG%       float64
3P        float64
3PA       float64
3P%       float64
2P        float64
2PA       float64
2P%       float64
eFG%      float64
FT        float64
FTA       float64
FT%       float64
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

In [18]:
len(dataframe_analyzed_df["Player"])

708

In [19]:
len(dataframe_analyzed_df["Player"].unique())

530

In [20]:
#print (660*3)

In [21]:
dataframe_analyzed_df[['Player','Age']].count()

Player    708
Age       708
dtype: int64

In [25]:
dataframe_analyzed_df[['Player','Age']]

                     Player  Age
0    √Ålex Abrines\abrinal01   25
1        Quincy Acy\acyqu01   28
2    Jaylen Adams\adamsja01   22
3    Steven Adams\adamsst01   25
4     Bam Adebayo\adebaba01   21
..                      ...  ...
703  Tyler Zeller\zellety01   29
704    Ante ≈Ωi≈æiƒá\zizican01   22
705   Ivica Zubac\zubaciv01   21
706   Ivica Zubac\zubaciv01   21
707   Ivica Zubac\zubaciv01   21

[708 rows x 2 columns]

In [22]:
# The follwoing section is to remove null values and
# create a new Dataframe which would hold clean data
player_stats_clean_df = dataframe_analyzed_df

In [23]:
# Get the count of rows
player_stats_clean_df.count()

Rk        708
Player    708
Pos       708
Age       708
Tm        708
G         708
GS        708
MP        708
FG        708
FGA       708
FG%       702
3P        708
3PA       708
3P%       661
2P        708
2PA       708
2P%       693
eFG%      702
FT        708
FTA       708
FT%       665
ORB       708
DRB       708
TRB       708
AST       708
STL       708
BLK       708
TOV       708
PF        708
PTS       708
dtype: int64

In [24]:
# Get the count of null values in each column
player_stats_clean_df.isnull().sum()

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        6
3P         0
3PA        0
3P%       47
2P         0
2PA        0
2P%       15
eFG%       6
FT         0
FTA        0
FT%       43
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
dtype: int64

In [25]:
# List the columns where NAN values needs to be replace with 0
player_stats_clean_df[['FG%','3P%','2P%','eFG%','FT%']]

       FG%    3P%    2P%   eFG%    FT%
0    0.357  0.323  0.500  0.487  0.923
1    0.222  0.133  0.667  0.278  0.700
2    0.345  0.338  0.361  0.459  0.778
3    0.595  0.000  0.596  0.595  0.500
4    0.576  0.200  0.588  0.579  0.735
..     ...    ...    ...    ...    ...
703  0.571    NaN  0.571  0.571  0.778
704  0.553    NaN  0.553  0.553  0.705
705  0.559    NaN  0.559  0.559  0.802
706  0.580    NaN  0.580  0.580  0.864
707  0.538    NaN  0.538  0.538  0.733

[708 rows x 5 columns]

In [26]:
# Summarize NAN count
player_stats_clean_df[['FG%','3P%','2P%','eFG%','FT%']].isnull().sum()

FG%      6
3P%     47
2P%     15
eFG%     6
FT%     43
dtype: int64

In [27]:
# Replace null values with 0
player_stats_clean_df[['FG%','3P%','2P%','eFG%','FT%']] = player_stats_clean_df[['FG%','3P%','2P%','eFG%','FT%']].fillna(value=0)

In [28]:
# Check whether the null values are replaced in new dataframe
player_stats_clean_df[['FG%','3P%','2P%','eFG%','FT%']].isnull().sum()

FG%     0
3P%     0
2P%     0
eFG%    0
FT%     0
dtype: int64

In [29]:
player_stats_clean_df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,√Ålex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,0.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,0.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,0.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,0.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,0.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,528,Tyler Zeller\zellety01,C,29,MEM,4,1,20.5,4.0,7.0,...,0.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
704,529,Ante ≈Ωi≈æiƒá\zizican01,C,22,CLE,59,25,18.3,3.1,5.6,...,0.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
705,530,Ivica Zubac\zubaciv01,C,21,TOT,59,37,17.6,3.6,6.4,...,0.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
706,530,Ivica Zubac\zubaciv01,C,21,LAL,33,12,15.6,3.4,5.8,...,0.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
707,530,Ivica Zubac\zubaciv01,C,21,LAC,26,25,20.2,3.8,7.2,...,0.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

In [30]:
#########################
# The following section is for splitting player_id and Playname into two columns
#########################

In [31]:
# Find datatype for playName column
player_stats_clean_df['Player'].dtypes

dtype('O')

In [32]:
# Put player name into a list
player_id_name = player_stats_clean_df['Player'].tolist()

In [33]:
# Split the playid and name and list the rows which are not split into 2 parts  with \ as delimeter(either 1 or >2)
for name in player_id_name:
    print(name.split("\\"), len(name.split("\\")))

['√Ålex Abrines', 'abrinal01'] 2
['Quincy Acy', 'acyqu01'] 2
['Jaylen Adams', 'adamsja01'] 2
['Steven Adams', 'adamsst01'] 2
['Bam Adebayo', 'adebaba01'] 2
['Deng Adel', 'adelde01'] 2
['DeVaughn Akoon-Purcell', 'akoonde01'] 2
['LaMarcus Aldridge', 'aldrila01'] 2
['Rawle Alkins', 'alkinra01'] 2
['Grayson Allen', 'allengr01'] 2
['Jarrett Allen', 'allenja01'] 2
['Kadeem Allen', 'allenka01'] 2
['Al-Farouq Aminu', 'aminual01'] 2
['Justin Anderson', 'anderju01'] 2
['Kyle Anderson', 'anderky01'] 2
['Ryan Anderson', 'anderry01'] 2
['Ryan Anderson', 'anderry01'] 2
['Ryan Anderson', 'anderry01'] 2
['Ike Anigbogu', 'anigbik01'] 2
['Giannis Antetokounmpo', 'antetgi01'] 2
['Kostas Antetokounmpo', 'antetko01'] 2
['Carmelo Anthony', 'anthoca01'] 2
['OG Anunoby', 'anunoog01'] 2
['Ryan Arcidiacono', 'arcidry01'] 2
['Trevor Ariza', 'arizatr01'] 2
['Trevor Ariza', 'arizatr01'] 2
['Trevor Ariza', 'arizatr01'] 2
['D.J. Augustin', 'augusdj01'] 2
['Deandre Ayton', 'aytonde01'] 2
['Dwayne Bacon', 'bacondw01'] 2
['Marvin Bagley III', 'baglema01'] 2
['Ron Baker', 'bakerro01'] 2
['Ron Baker', 'bakerro01'] 2
['Ron Baker', 'bakerro01'] 2
['Wade Baldwin', 'baldwwa01'] 2
['Lonzo Ball', 'balllo01'] 2
['Mo Bamba', 'bambamo01'] 2
['J.J. Barea', 'bareajo01'] 2
['Harrison Barnes', 'barneha02'] 2
['Harrison Barnes', 'barneha02'] 2
['Harrison Barnes', 'barneha02'] 2
['Will Barton', 'bartowi01'] 2
['Keita Bates-Diop', 'bateske01'] 2
['Nicolas Batum', 'batumni01'] 2
['Jerryd Bayless', 'bayleje01'] 2
['Aron Baynes', 'baynear01'] 2
['Kent Bazemore', 'bazemke01'] 2
['Bradley Beal', 'bealbr01'] 2
['Malik Beasley', 'beaslma01'] 2
['Michael Beasley', 'beaslmi01'] 2
['Marco Belinelli', 'belinma01'] 2
['Jordan Bell', 'belljo01'] 2
["DeAndre' Bembry", 'bembrde01'] 2
['Dragan Bender', 'bendedr01'] 2
['Dairis BertƒÅns', 'bertada02'] 2
['DƒÅvis BertƒÅns', 'bertada01'] 2
['Patrick Beverley', 'beverpa01'] 2
['Khem Birch', 'birchkh01'] 2
['Bismack Biyombo', 'biyombi01'] 2
['Nemanja Bjelica', 'bjeline01'] 2
['Antonio Blakeney', 'blakean01'] 2
['Eric Bledsoe', 'bledser01'] 2
['Jaron Blossomgame', 'blossja01'] 2
['Bogdan Bogdanoviƒá', 'bogdabo01'] 2
['Bojan Bogdanoviƒá', 'bogdabo02'] 2
['Andrew Bogut', 'bogutan01'] 2
['Jonah Bolden', 'boldejo01'] 2
['Isaac Bonga', 'bongais01'] 2
['Devin Booker', 'bookede01'] 2
['Chris Boucher', 'bouchch01'] 2
['Avery Bradley', 'bradlav01'] 2
['Avery Bradley', 'bradlav01'] 2
['Avery Bradley', 'bradlav01'] 2
['Tony Bradley', 'bradlto01'] 2
['Corey Brewer', 'breweco01'] 2
['Corey Brewer', 'breweco01'] 2
['Corey Brewer', 'breweco01'] 2
['Mikal Bridges', 'bridgmi01'] 2
['Miles Bridges', 'bridgmi02'] 2
['Isaiah Briscoe', 'briscis01'] 2
['Ryan Broekhoff', 'broekry01'] 2
['Malcolm Brogdon', 'brogdma01'] 2
['Dillon Brooks', 'brookdi01'] 2
['MarShon Brooks', 'brookma01'] 2
['Bruce Brown', 'brownbr01'] 2
['Jaylen Brown', 'brownja02'] 2
['Lorenzo Brown', 'brownlo01'] 2
['Sterling Brown', 'brownst02'] 2
['Troy Brown Jr.', 'browntr01'] 2
['Jalen Brunson', 'brunsja01'] 2
['Thomas Bryant', 'bryanth01'] 2
['Reggie Bullock', 'bullore01'] 2
['Reggie Bullock', 'bullore01'] 2
['Reggie Bullock', 'bullore01'] 2
['Trey Burke', 'burketr01'] 2
['Trey Burke', 'burketr01'] 2
['Trey Burke', 'burketr01'] 2
['Alec Burks', 'burksal01'] 2
['Alec Burks', 'burksal01'] 2
['Alec Burks', 'burksal01'] 2
['Alec Burks', 'burksal01'] 2
['Deonte Burton', 'burtode02'] 2
['Jimmy Butler', 'butleji01'] 2
['Jimmy Butler', 'butleji01'] 2
['Jimmy Butler', 'butleji01'] 2
['Bruno Caboclo', 'cabocbr01'] 2
['Jos√© Calder√≥n', 'caldejo01'] 2
['Kentavious Caldwell-Pope', 'caldwke01'] 2
['Isaiah Canaan', 'canaais01'] 2
['Isaiah Canaan', 'canaais01'] 2
['Isaiah Canaan', 'canaais01'] 2
['Isaiah Canaan', 'canaais01'] 2
['Clint Capela', 'capelca01'] 2
['DeMarre Carroll', 'carrode01'] 2
['Jevon Carter', 'carteje01'] 2
['Vince Carter', 'cartevi01'] 2
['Wendell Carter Jr.', 'cartewe01'] 2
['Michael Carter-Williams', 'cartemi01'] 2
['Michael Carter-Williams', 'cartemi01'] 2
['Michael Carter-Williams', 'cartemi01'] 2
['Alex Caruso', 'carusal01'] 2
['Omri Casspi', 'casspom01'] 2
['Willie Cauley-Stein', 'caulewi01'] 2
['Troy Caupain', 'caupatr01'] 2
['Tyler Cavanaugh', 'cavanty01'] 2
['Tyson Chandler', 'chandty01'] 2
['Tyson Chandler', 'chandty01'] 2
['Tyson Chandler', 'chandty01'] 2
['Wilson Chandler', 'chandwi01'] 2
['Wilson Chandler', 'chandwi01'] 2
['Wilson Chandler', 'chandwi01'] 2
['Joe Chealey', 'chealjo01'] 2
['Chris Chiozza', 'chiozch01'] 2
['Marquese Chriss', 'chrisma01'] 2
['Marquese Chriss', 'chrisma01'] 2
['Marquese Chriss', 'chrisma01'] 2
['Gary Clark', 'clarkga01'] 2
['Ian Clark', 'clarkia01'] 2
['Jordan Clarkson', 'clarkjo01'] 2
['John Collins', 'collijo01'] 2
['Zach Collins', 'colliza01'] 2
['Darren Collison', 'collida01'] 2
['Bonzie Colson', 'colsobo01'] 2
['Mike Conley', 'conlemi01'] 2
['Pat Connaughton', 'connapa01'] 2
['Quinn Cook', 'cookqu01'] 2
['DeMarcus Cousins', 'couside01'] 2
['Robert Covington', 'covinro01'] 2
['Robert Covington', 'covinro01'] 2
['Robert Covington', 'covinro01'] 2
['Allen Crabbe', 'crabbal01'] 2
['Torrey Craig', 'craigto01'] 2
['Jamal Crawford', 'crawfja01'] 2
['Mitch Creek', 'creekmi01'] 2
['Mitch Creek', 'creekmi01'] 2
['Mitch Creek', 'creekmi01'] 2
['Jae Crowder', 'crowdja01'] 2
['Dante Cunningham', 'cunnida01'] 2
['Seth Curry', 'curryse01'] 2
['Stephen Curry', 'curryst01'] 2
['Troy Daniels', 'danietr01'] 2
['Anthony Davis', 'davisan02'] 2
['Deyonta Davis', 'davisde01'] 2
['Ed Davis', 'davised01'] 2
['Tyler Davis', 'davisty01'] 2
['Dewayne Dedmon', 'dedmode01'] 2
['Sam Dekker', 'dekkesa01'] 2
['Sam Dekker', 'dekkesa01'] 2
['Sam Dekker', 'dekkesa01'] 2
['√Ångel Delgado', 'delgaan01'] 2
['Matthew Dellavedova', 'dellama01'] 2
['Matthew Dellavedova', 'dellama01'] 2
['Matthew Dellavedova', 'dellama01'] 2
['Luol Deng', 'denglu01'] 2
['DeMar DeRozan', 'derozde01'] 2
['Marcus Derrickson', 'derrima01'] 2
['Cheick Diallo', 'diallch01'] 2
['Hamidou Diallo', 'diallha01'] 2
['Gorgui Dieng', 'dienggo01'] 2
['Spencer Dinwiddie', 'dinwisp01'] 2
['Donte DiVincenzo', 'divindo01'] 2
['Luka Donƒçiƒá', 'doncilu01'] 2
['Tyler Dorsey', 'dorsety01'] 2
['Tyler Dorsey', 'dorsety01'] 2
['Tyler Dorsey', 'dorsety01'] 2
['Damyean Dotson', 'dotsoda01'] 2
['PJ Dozier', 'doziepj01'] 2
['Goran Dragiƒá', 'dragigo01'] 2
['Andre Drummond', 'drumman01'] 2
['Jared Dudley', 'dudleja01'] 2
['Kris Dunn', 'dunnkr01'] 2
['Kevin Durant', 'duranke01'] 2
['Trevon Duval', 'duvaltr01'] 2
['Vince Edwards', 'edwarvi01'] 2
['Henry Ellenson', 'ellenhe01'] 2
['Henry Ellenson', 'ellenhe01'] 2
['Henry Ellenson', 'ellenhe01'] 2
['Wayne Ellington', 'ellinwa01'] 2
['Wayne Ellington', 'ellinwa01'] 2
['Wayne Ellington', 'ellinwa01'] 2
['Joel Embiid', 'embiijo01'] 2
['James Ennis', 'ennisja01'] 2
['James Ennis', 'ennisja01'] 2
['James Ennis', 'ennisja01'] 2
['Drew Eubanks', 'eubandr01'] 2
['Jacob Evans', 'evansja02'] 2
['Jawun Evans', 'evansja01'] 2
['Jawun Evans', 'evansja01'] 2
['Jawun Evans', 'evansja01'] 2
['Tyreke Evans', 'evansty01'] 2
['Dante Exum', 'exumda01'] 2
['Kenneth Faried', 'farieke01'] 2
['Kenneth Faried', 'farieke01'] 2
['Kenneth Faried', 'farieke01'] 2
['Derrick Favors', 'favorde01'] 2
['Cristiano Fel√≠cio', 'feliccr01'] 2
['Raymond Felton', 'feltora01'] 2
['Terrance Ferguson', 'fergute01'] 2
['Yogi Ferrell', 'ferreyo01'] 2
['Dorian Finney-Smith', 'finnedo01'] 2
['Bryn Forbes', 'forbebr01'] 2
['Evan Fournier', 'fournev01'] 2
["De'Aaron Fox", 'foxde01'] 2
['Melvin Frazier', 'frazime01'] 2
['Tim Frazier', 'fraziti01'] 2
['Tim Frazier', 'fraziti01'] 2
['Tim Frazier', 'fraziti01'] 2
['Jimmer Fredette', 'fredeji01'] 2
['Channing Frye', 'fryech01'] 2
['Markelle Fultz', 'fultzma01'] 2
['Danilo Gallinari', 'gallida01'] 2
['Langston Galloway', 'gallola01'] 2
['Billy Garrett', 'garrebi01'] 2
['Marc Gasol', 'gasolma01'] 2
['Marc Gasol', 'gasolma01'] 2
['Marc Gasol', 'gasolma01'] 2
['Pau Gasol', 'gasolpa01'] 2
['Pau Gasol', 'gasolpa01'] 2
['Pau Gasol', 'gasolpa01'] 2
['Rudy Gay', 'gayru01'] 2
['Paul George', 'georgpa01'] 2
['Taj Gibson', 'gibsota01'] 2
['Harry Giles', 'gilesha01'] 2
['Shai Gilgeous-Alexander', 'gilgesh01'] 2
['Rudy Gobert', 'goberru01'] 2
['Brandon Goodwin', 'goodwbr01'] 2
['Aaron Gordon', 'gordoaa01'] 2
['Eric Gordon', 'gordoer01'] 2
['Marcin Gortat', 'gortama01'] 2
["Devonte' Graham", 'grahade01'] 2
['Treveon Graham', 'grahatr01'] 2
['Jerami Grant', 'grantje01'] 2
['Jerian Grant', 'grantje02'] 2
['Donte Grantham', 'grantdo01'] 2
['Danny Green', 'greenda02'] 2
['Draymond Green', 'greendr01'] 2
['Gerald Green', 'greenge01'] 2
['JaMychal Green', 'greenja01'] 2
['JaMychal Green', 'greenja01'] 2
['JaMychal Green', 'greenja01'] 2
['Jeff Green', 'greenje02'] 2
['Blake Griffin', 'griffbl01'] 2
['Daniel Hamilton', 'hamilda02'] 2
['Dusty Hannahs', 'hannadu01'] 2
['Tim Hardaway Jr.', 'hardati02'] 2
['Tim Hardaway Jr.', 'hardati02'] 2
['Tim Hardaway Jr.', 'hardati02'] 2
['James Harden', 'hardeja01'] 2
['Maurice Harkless', 'harklma01'] 2
['Montrezl Harrell', 'harremo01'] 2
['Devin Harris', 'harride01'] 2
['Gary Harris', 'harriga01'] 2
['Joe Harris', 'harrijo01'] 2
['Tobias Harris', 'harrito02'] 2
['Tobias Harris', 'harrito02'] 2
['Tobias Harris', 'harrito02'] 2
['Andrew Harrison', 'harrian01'] 2
['Andrew Harrison', 'harrian01'] 2
['Andrew Harrison', 'harrian01'] 2
['Andrew Harrison', 'harrian01'] 2
['Shaquille Harrison', 'harrish01'] 2
['Josh Hart', 'hartjo01'] 2
['Isaiah Hartenstein', 'harteis01'] 2
['Udonis Haslem', 'hasleud01'] 2
['Gordon Hayward', 'haywago01'] 2
['John Henson', 'hensojo01'] 2
['Juan Hernang√≥mez', 'hernaju01'] 2
['Willy Hernang√≥mez', 'hernawi01'] 2
['Mario Hezonja', 'hezonma01'] 2
['Isaiah Hicks', 'hicksis01'] 2
['Buddy Hield', 'hieldbu01'] 2
['Haywood Highsmith', 'highsha01'] 2
['Nen√™', 'hilarne01'] 2
['George Hill', 'hillge01'] 2
['George Hill', 'hillge01'] 2
['George Hill', 'hillge01'] 2
['Solomon Hill', 'hillso01'] 2
['Aaron Holiday', 'holidaa01'] 2
['Jrue Holiday', 'holidjr01'] 2
['Justin Holiday', 'holidju01'] 2
['Justin Holiday', 'holidju01'] 2
['Justin Holiday', 'holidju01'] 2
['John Holland', 'hollajo02'] 2
['Rondae Hollis-Jefferson', 'holliro01'] 2
['Richaun Holmes', 'holmeri01'] 2
['Rodney Hood', 'hoodro01'] 2
['Rodney Hood', 'hoodro01'] 2
['Rodney Hood', 'hoodro01'] 2
['Al Horford', 'horfoal01'] 2
['Danuel House', 'houseda01'] 2
['Dwight Howard', 'howardw01'] 2
['Kevin Huerter', 'huertke01'] 2
['Isaac Humphries', 'humphis01'] 2
['R.J. Hunter', 'hunterj01'] 2
['Chandler Hutchison', 'hutchch01'] 2
['Serge Ibaka', 'ibakase01'] 2
['Andre Iguodala', 'iguodan01'] 2
['Ersan ƒ∞lyasova', 'ilyaser01'] 2
['Joe Ingles', 'inglejo01'] 2
['Andre Ingram', 'ingraan01'] 2
['Brandon Ingram', 'ingrabr01'] 2
['Kyrie Irving', 'irvinky01'] 2
['Jonathan Isaac', 'isaacjo01'] 2
['Wesley Iwundu', 'iwundwe01'] 2
['Demetrius Jackson', 'jacksde01'] 2
['Frank Jackson', 'jacksfr01'] 2
['Jaren Jackson Jr.', 'jacksja02'] 2
['Josh Jackson', 'jacksjo02'] 2
['Justin Jackson', 'jacksju01'] 2
['Justin Jackson', 'jacksju01'] 2
['Justin Jackson', 'jacksju01'] 2
['Reggie Jackson', 'jacksre01'] 2
['LeBron James', 'jamesle01'] 2
['Amile Jefferson', 'jeffeam01'] 2
['John Jenkins', 'jenkijo01'] 2
['John Jenkins', 'jenkijo01'] 2
['John Jenkins', 'jenkijo01'] 2
['Jonas Jerebko', 'jerebjo01'] 2
['Alize Johnson', 'johnsal02'] 2
['Amir Johnson', 'johnsam01'] 2
['B.J. Johnson', 'johnsbj01'] 2
['B.J. Johnson', 'johnsbj01'] 2
['B.J. Johnson', 'johnsbj01'] 2
['James Johnson', 'johnsja01'] 2
['Stanley Johnson', 'johnsst04'] 2
['Stanley Johnson', 'johnsst04'] 2
['Stanley Johnson', 'johnsst04'] 2
['Tyler Johnson', 'johnsty01'] 2
['Tyler Johnson', 'johnsty01'] 2
['Tyler Johnson', 'johnsty01'] 2
['Wesley Johnson', 'johnswe01'] 2
['Wesley Johnson', 'johnswe01'] 2
['Wesley Johnson', 'johnswe01'] 2
['Nikola Jokiƒá', 'jokicni01'] 2
['Damian Jones', 'jonesda03'] 2
['Derrick Jones Jr.', 'jonesde02'] 2
['Jalen Jones', 'jonesja04'] 2
['Jemerrio Jones', 'jonesje01'] 2
['Terrence Jones', 'joneste01'] 2
['Tyus Jones', 'jonesty01'] 2
['DeAndre Jordan', 'jordade01'] 2
['DeAndre Jordan', 'jordade01'] 2
['DeAndre Jordan', 'jordade01'] 2
['Cory Joseph', 'josepco01'] 2
['Frank Kaminsky', 'kaminfr01'] 2
['Enes Kanter', 'kanteen01'] 2
['Enes Kanter', 'kanteen01'] 2
['Enes Kanter', 'kanteen01'] 2
['Luke Kennard', 'kennalu01'] 2
['Michael Kidd-Gilchrist', 'kiddgmi01'] 2
['George King', 'kingge03'] 2
['Maxi Kleber', 'klebima01'] 2
['Brandon Knight', 'knighbr03'] 2
['Brandon Knight', 'knighbr03'] 2
['Brandon Knight', 'knighbr03'] 2
['Kevin Knox', 'knoxke01'] 2
['Furkan Korkmaz', 'korkmfu01'] 2
['Luke Kornet', 'kornelu01'] 2
['Kyle Korver', 'korveky01'] 2
['Kyle Korver', 'korveky01'] 2
['Kyle Korver', 'korveky01'] 2
['Kosta Koufos', 'koufoko01'] 2
['Rodions Kurucs', 'kurucro01'] 2
['Kyle Kuzma', 'kuzmaky01'] 2
['Skal Labissi√®re', 'labissk01'] 2
['Skal Labissi√®re', 'labissk01'] 2
['Skal Labissi√®re', 'labissk01'] 2
['Jeremy Lamb', 'lambje01'] 2
['Zach LaVine', 'lavinza01'] 2
['Jake Layman', 'laymaja01'] 2
['T.J. Leaf', 'leaftj01'] 2
['Courtney Lee', 'leeco01'] 2
['Courtney Lee', 'leeco01'] 2
['Courtney Lee', 'leeco01'] 2
['Damion Lee', 'leeda03'] 2
['Walt Lemon Jr.', 'lemonwa01'] 2
['Alex Len', 'lenal01'] 2
['Kawhi Leonard', 'leonaka01'] 2
['Meyers Leonard', 'leoname01'] 2
['Jon Leuer', 'leuerjo01'] 2
['Caris LeVert', 'leverca01'] 2
['Damian Lillard', 'lillada01'] 2
['Jeremy Lin', 'linje01'] 2
['Jeremy Lin', 'linje01'] 2
['Jeremy Lin', 'linje01'] 2
['Shaun Livingston', 'livinsh01'] 2
['Zach Lofton', 'loftoza01'] 2
['Kevon Looney', 'looneke01'] 2
['Brook Lopez', 'lopezbr01'] 2
['Robin Lopez', 'lopezro01'] 2
['Kevin Love', 'loveke01'] 2
['Kyle Lowry', 'lowryky01'] 2
['Jordan Loyd', 'loydjo01'] 2
['Kalin Lucas', 'lucaska01'] 2
['Timoth√© Luwawu-Cabarrot', 'luwawti01'] 2
['Timoth√© Luwawu-Cabarrot', 'luwawti01'] 2
['Timoth√© Luwawu-Cabarrot', 'luwawti01'] 2
['Tyler Lydon', 'lydonty01'] 2
['Trey Lyles', 'lylestr01'] 2
['Scott Machado', 'machasc01'] 2
['Shelvin Mack', 'macksh01'] 2
['Shelvin Mack', 'macksh01'] 2
['Shelvin Mack', 'macksh01'] 2
['Daryl Macon', 'maconda01'] 2
['J.P. Macura', 'macurjp01'] 2
['Ian Mahinmi', 'mahinia01'] 2
['Thon Maker', 'makerth01'] 2
['Thon Maker', 'makerth01'] 2
['Thon Maker', 'makerth01'] 2
['Boban Marjanoviƒá', 'marjabo01'] 2
['Boban Marjanoviƒá', 'marjabo01'] 2
['Boban Marjanoviƒá', 'marjabo01'] 2
['Lauri Markkanen', 'markkla01'] 2
['Jarell Martin', 'martija01'] 2
['Frank Mason III', 'masonfr01'] 2
['Yante Maten', 'matenya01'] 2
['Wesley Matthews', 'matthwe02'] 2
['Wesley Matthews', 'matthwe02'] 2
['Wesley Matthews', 'matthwe02'] 2
['Wesley Matthews', 'matthwe02'] 2
['Luc Mbah a Moute', 'mbahalu01'] 2
['Tahjere McCall', 'mccalta01'] 2
['Patrick McCaw', 'mccawpa01'] 2
['Patrick McCaw', 'mccawpa01'] 2
['Patrick McCaw', 'mccawpa01'] 2
['CJ McCollum', 'mccolcj01'] 2
['T.J. McConnell', 'mccontj01'] 2
['Doug McDermott', 'mcderdo01'] 2
['JaVale McGee', 'mcgeeja01'] 2
['Rodney McGruder', 'mcgruro01'] 2
['Alfonzo McKinnie', 'mckinal01'] 2
['Ben McLemore', 'mclembe01'] 2
['Jordan McRae', 'mcraejo01'] 2
['Jodie Meeks', 'meeksjo01'] 2
['Salah Mejri', 'mejrisa01'] 2
["De'Anthony Melton", 'meltode01'] 2
['Chimezie Metu', 'metuch01'] 2
['Khris Middleton', 'middlkh01'] 2
['C.J. Miles', 'milescj01'] 2
['C.J. Miles', 'milescj01'] 2
['C.J. Miles', 'milescj01'] 2
['Darius Miller', 'milleda01'] 2
['Malcolm Miller', 'millema01'] 2
['Patty Mills', 'millspa02'] 2
['Paul Millsap', 'millspa01'] 2
['Shake Milton', 'miltosh01'] 2
['Nikola Mirotiƒá', 'mirotni01'] 2
['Nikola Mirotiƒá', 'mirotni01'] 2
['Nikola Mirotiƒá', 'mirotni01'] 2
['Donovan Mitchell', 'mitchdo01'] 2
['Naz Mitrou-Long', 'mitrona01'] 2
['Malik Monk', 'monkma01'] 2
['Greg Monroe', 'monrogr01'] 2
['Greg Monroe', 'monrogr01'] 2
['Greg Monroe', 'monrogr01'] 2
['Greg Monroe', 'monrogr01'] 2
["E'Twaun Moore", 'mooreet01'] 2
['Eric Moreland', 'moreler01'] 2
['Eric Moreland', 'moreler01'] 2
['Eric Moreland', 'moreler01'] 2
['Jaylen Morris', 'morrija01'] 2
['Marcus Morris', 'morrima03'] 2
['Markieff Morris', 'morrima02'] 2
['Markieff Morris', 'morrima02'] 2
['Markieff Morris', 'morrima02'] 2
['Monte Morris', 'morrimo01'] 2
['Donatas Motiej≈´nas', 'motiedo01'] 2
['Johnathan Motley', 'motlejo01'] 2
['Emmanuel Mudiay', 'mudiaem01'] 2
['Jamal Murray', 'murraja01'] 2
['D≈æanan Musa', 'musadz01'] 2
['Mike Muscala', 'muscami01'] 2
['Mike Muscala', 'muscami01'] 2
['Mike Muscala', 'muscami01'] 2
['Sviatoslav Mykhailiuk', 'mykhasv01'] 2
['Sviatoslav Mykhailiuk', 'mykhasv01'] 2
['Sviatoslav Mykhailiuk', 'mykhasv01'] 2
['Abdel Nader', 'naderab01'] 2
['Larry Nance Jr.', 'nancela02'] 2
['Shabazz Napier', 'napiesh01'] 2
['Raul Neto', 'netora01'] 2
['Georges Niang', 'niangge01'] 2
['Joakim Noah', 'noahjo01'] 2
['Nerlens Noel', 'noelne01'] 2
['Dirk Nowitzki', 'nowitdi01'] 2
['Frank Ntilikina', 'ntilila01'] 2
['James Nunnally', 'nunnaja01'] 2
['James Nunnally', 'nunnaja01'] 2
['James Nunnally', 'nunnaja01'] 2
['Jusuf Nurkiƒá', 'nurkiju01'] 2
['David Nwaba', 'nwabada01'] 2
["Royce O'Neale", 'onealro01'] 2
["Kyle O'Quinn", 'oquinky01'] 2
['Semi Ojeleye', 'ojelese01'] 2
['Jahlil Okafor', 'okafoja01'] 2
['Elie Okobo', 'okoboel01'] 2
['Josh Okogie', 'okogijo01'] 2
['Victor Oladipo', 'oladivi01'] 2
['Kelly Olynyk', 'olynyke01'] 2
['Cedi Osman', 'osmande01'] 2
['Kelly Oubre Jr.', 'oubreke01'] 2
['Kelly Oubre Jr.', 'oubreke01'] 2
['Kelly Oubre Jr.', 'oubreke01'] 2
['Zaza Pachulia', 'pachuza01'] 2
['Jabari Parker', 'parkeja01'] 2
['Jabari Parker', 'parkeja01'] 2
['Jabari Parker', 'parkeja01'] 2
['Tony Parker', 'parketo01'] 2
['Chandler Parsons', 'parsoch01'] 2
['Patrick Patterson', 'pattepa01'] 2
['Justin Patton', 'pattoju01'] 2
['Chris Paul', 'paulch01'] 2
['Cameron Payne', 'payneca01'] 2
['Cameron Payne', 'payneca01'] 2
['Cameron Payne', 'payneca01'] 2
['Elfrid Payton', 'paytoel01'] 2
['Gary Payton II', 'paytoga02'] 2
['Theo Pinson', 'pinsoth01'] 2
['Mason Plumlee', 'plumlma01'] 2
['Miles Plumlee', 'plumlmi01'] 2
['Jakob Poeltl', 'poeltja01'] 2
['Quincy Pondexter', 'pondequ01'] 2
['Otto Porter', 'porteot01'] 2
['Otto Porter', 'porteot01'] 2
['Otto Porter', 'porteot01'] 2
['Bobby Portis', 'portibo01'] 2
['Bobby Portis', 'portibo01'] 2
['Bobby Portis', 'portibo01'] 2
['Dwight Powell', 'poweldw01'] 2
['Norman Powell', 'powelno01'] 2
['Alex Poythress', 'poythal01'] 2
['Zhou Qi', 'qizh01'] 2
['Ivan Rabb', 'rabbiv01'] 2
['Chasson Randle', 'randlch01'] 2
['Julius Randle', 'randlju01'] 2
['J.J. Redick', 'redicjj01'] 2
['Davon Reed', 'reedda01'] 2
['Cameron Reynolds', 'reynoca01'] 2
['Josh Richardson', 'richajo01'] 2
['Malachi Richardson', 'richama01'] 2
['Austin Rivers', 'riverau01'] 2
['Austin Rivers', 'riverau01'] 2
['Austin Rivers', 'riverau01'] 2
['Devin Robinson', 'robinde01'] 2
['Duncan Robinson', 'robindu01'] 2
['Glenn Robinson III', 'robingl02'] 2
['Jerome Robinson', 'robinje01'] 2
['Mitchell Robinson', 'robinmi01'] 2
['Rajon Rondo', 'rondora01'] 2
['Derrick Rose', 'rosede01'] 2
['Terrence Ross', 'rosste01'] 2
['Terry Rozier', 'roziete01'] 2
['Ricky Rubio', 'rubiori01'] 2
["D'Angelo Russell", 'russeda01'] 2
['Domantas Sabonis', 'sabondo01'] 2
['Brandon Sampson', 'sampsbr01'] 2
['JaKarr Sampson', 'sampsja02'] 2
['Dario ≈†ariƒá', 'saricda01'] 2
['Dario ≈†ariƒá', 'saricda01'] 2
['Dario ≈†ariƒá', 'saricda01'] 2
['Tom√°≈° Satoransk√Ω', 'satorto01'] 2
['Dennis Schr√∂der', 'schrode01'] 2
['Mike Scott', 'scottmi01'] 2
['Mike Scott', 'scottmi01'] 2
['Mike Scott', 'scottmi01'] 2
['Thabo Sefolosha', 'sefolth01'] 2
['Wayne Selden', 'seldewa01'] 2
['Wayne Selden', 'seldewa01'] 2
['Wayne Selden', 'seldewa01'] 2
['Collin Sexton', 'sextoco01'] 2
['Landry Shamet', 'shamela01'] 2
['Landry Shamet', 'shamela01'] 2
['Landry Shamet', 'shamela01'] 2
['Iman Shumpert', 'shumpim01'] 2
['Iman Shumpert', 'shumpim01'] 2
['Iman Shumpert', 'shumpim01'] 2
['Pascal Siakam', 'siakapa01'] 2
['Jordan Sibert', 'siberjo01'] 2
['Ben Simmons', 'simmobe01'] 2
['Jonathon Simmons', 'simmojo02'] 2
['Jonathon Simmons', 'simmojo02'] 2
['Jonathon Simmons', 'simmojo02'] 2
['Kobi Simmons', 'simmoko01'] 2
['Anfernee Simons', 'simonan01'] 2

In [34]:
# Split the playid and name and list the rows which are not split into 2 parts (either 1 or >2)
for name in player_id_name:
    if (len(name.split("\\")) != 2):
        print(name.split("\\"), len(name.split("\\")))

In [35]:
# Adjust split argument to check whether our code wortks by changing delimeter to space
# Split the playid and name and list the rows which are not split into 2 parts (either 1 or >2)
for name in player_id_name:
    if len(name.split()) != 2:
        print(name.split(), len(name.split()))
# could see that all rows are split into 2 (not less, not more)

['Marvin', 'Bagley', 'III\\baglema01'] 3
['Troy', 'Brown', 'Jr.\\browntr01'] 3
['Wendell', 'Carter', 'Jr.\\cartewe01'] 3
['Tim', 'Hardaway', 'Jr.\\hardati02'] 3
['Tim', 'Hardaway', 'Jr.\\hardati02'] 3
['Tim', 'Hardaway', 'Jr.\\hardati02'] 3
['Nen√™\\hilarne01'] 1
['Jaren', 'Jackson', 'Jr.\\jacksja02'] 3
['Derrick', 'Jones', 'Jr.\\jonesde02'] 3
['Walt', 'Lemon', 'Jr.\\lemonwa01'] 3
['Frank', 'Mason', 'III\\masonfr01'] 3
['Luc', 'Mbah', 'a', 'Moute\\mbahalu01'] 4
['Larry', 'Nance', 'Jr.\\nancela02'] 3
['Kelly', 'Oubre', 'Jr.\\oubreke01'] 3
['Kelly', 'Oubre', 'Jr.\\oubreke01'] 3
['Kelly', 'Oubre', 'Jr.\\oubreke01'] 3
['Gary', 'Payton', 'II\\paytoga02'] 3
['Glenn', 'Robinson', 'III\\robingl02'] 3
['Dennis', 'Smith', 'Jr.\\smithde03'] 3
['Dennis', 'Smith', 'Jr.\\smithde03'] 3
['Dennis', 'Smith', 'Jr.\\smithde03'] 3
['Gary', 'Trent', 'Jr.\\trentga02'] 3

In [36]:
# Splits the Name Column into two columns and add it to Dataframe
split_name_df = player_stats_clean_df['Player'].str.split("\\", n = 1, expand = True)
split_name_df

                0          1
0    √Ålex Abrines  abrinal01
1      Quincy Acy    acyqu01
2    Jaylen Adams  adamsja01
3    Steven Adams  adamsst01
4     Bam Adebayo  adebaba01
..            ...        ...
703  Tyler Zeller  zellety01
704    Ante ≈Ωi≈æiƒá  zizican01
705   Ivica Zubac  zubaciv01
706   Ivica Zubac  zubaciv01
707   Ivica Zubac  zubaciv01

[708 rows x 2 columns]

In [37]:
split_name_df.dtypes

0    object
1    object
dtype: object

In [38]:
# Add New column called player_name
player_stats_clean_df["player_name"] = split_name_df[0]
player_stats_clean_df["player_id"] = split_name_df[1]

In [39]:
# Verify whether new columns are added to the Dataframe
player_stats_clean_df.dtypes

Rk               int64
Player          object
Pos             object
Age              int64
Tm              object
G                int64
GS               int64
MP             float64
FG             float64
FGA            float64
FG%            float64
3P             float64
3PA            float64
3P%            float64
2P             float64
2PA            float64
2P%            float64
eFG%           float64
FT             float64
FTA            float64
FT%            float64
ORB            float64
DRB            float64
TRB            float64
AST            float64
STL            float64
BLK            float64
TOV            float64
PF             float64
PTS            float64
player_name     object
player_id       object
dtype: object

In [40]:
player_stats_clean_df['player_id']

0      abrinal01
1        acyqu01
2      adamsja01
3      adamsst01
4      adebaba01
         ...
703    zellety01
704    zizican01
705    zubaciv01
706    zubaciv01
707    zubaciv01
Name: player_id, Length: 708, dtype: object

In [ ]:
################################################################################
# The following section is to identify players who got traded in the middle of a season and clean it up
# the players will have multiple rows
# pick the row that has TOT for team. 
################################################################################

In [41]:
# Find Frequency of occurence of a players name
duplicate_name_df = player_stats_clean_df['player_id'].groupby(player_stats_clean_df['player_id']).count()
duplicate_name_df

player_id
abrinal01    1
acyqu01      1
adamsja01    1
adamsst01    1
adebaba01    1
            ..
youngtr01    1
zelleco01    1
zellety01    3
zizican01    1
zubaciv01    3
Name: player_id, Length: 530, dtype: int64

In [42]:
# Filter names if they are repeasted duplicate_name_df
for player_id in duplicate_name_df:
    print(player_id)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
3
1
1
1
1
3
1
1
1
1
3
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
1
3
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
3
4
1
3
1
1
1
4
1
1
1
3
1
1
1
1
1
1
1
3
3
1
1
3
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
3
1
1
1
1
1
1
1
1
1
1
3
1
3
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
1
1
1
3
3
1
3
1
3
1
1
1
3
1
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
3
3
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
1
3
1
1
1
4
1
1
1
1
3
1
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
3
1
1
1
3
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
3
1
1
1
3
1
3
3
3
1
1
1
1
1
1
1
3
1
1
3
1
1
1
1
3
1
1
1
3
1
1
1
3
1
1
1
1
3
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
1
1
1
3
1
1
1
3
1
1
1
3
3
1
1
1
1
4
1
1
3
1
1
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
3
1
1
1
4
1
3
1
3
1
1
1
1
1
1
1
3
3
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
1
1
1
1
1
3
1
3
1
1
1
1
1
3
1
1
1
1
1
1
1
3
3
1
1
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
1
1
3
1
3
1
3
3
1
1
1
3
1
1
1
3
1
4
1
1
1
3
1
3
1
1
1
3
1
1
3
1
1
3
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
3
3
1
1
1
1
1
3
1
3

In [43]:
# Another way to find frequency
duplicate_name_2_df = player_stats_clean_df['player_id'].value_counts()
duplicate_name_2_df

smithja02    4
matthwe02    4
canaais01    4
burksal01    4
monrogr01    4
            ..
feliccr01    1
vanvlfr01    1
rondora01    1
hillso01     1
jerebjo01    1
Name: player_id, Length: 530, dtype: int64

In [44]:
duplicate_name_2_df.dtypes

dtype('int64')

In [45]:
# Number of players who are traded (and have multiple rows)
duplicate_name_2_df.loc[(duplicate_name_2_df >1)].count()

86

In [46]:
# Use the second method to create a column in 
player_stats_clean_df["player_frequency"]  = player_stats_clean_df.player_id.map(player_stats_clean_df.player_id.value_counts())
player_stats_clean_df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,player_name,player_id,player_frequency
0,1,√Ålex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,1.5,0.6,0.5,0.2,0.5,1.7,5.3,√Ålex Abrines,abrinal01,1
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,2.5,0.8,0.1,0.4,0.4,2.4,1.7,Quincy Acy,acyqu01,1
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,1.8,1.9,0.4,0.1,0.8,1.3,3.2,Jaylen Adams,adamsja01,1
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,9.5,1.6,1.5,1.0,1.7,2.6,13.9,Steven Adams,adamsst01,1
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,7.3,2.2,0.9,0.8,1.5,2.5,8.9,Bam Adebayo,adebaba01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,528,Tyler Zeller\zellety01,C,29,MEM,4,1,20.5,4.0,7.0,...,4.5,0.8,0.3,0.8,1.0,4.0,11.5,Tyler Zeller,zellety01,3
704,529,Ante ≈Ωi≈æiƒá\zizican01,C,22,CLE,59,25,18.3,3.1,5.6,...,5.4,0.9,0.2,0.4,1.0,1.9,7.8,Ante ≈Ωi≈æiƒá,zizican01,1
705,530,Ivica Zubac\zubaciv01,C,21,TOT,59,37,17.6,3.6,6.4,...,6.1,1.1,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,zubaciv01,3
706,530,Ivica Zubac\zubaciv01,C,21,LAL,33,12,15.6,3.4,5.8,...,4.9,0.8,0.1,0.8,1.0,2.2,8.5,Ivica Zubac,zubaciv01,3
707,530,Ivica Zubac\zubaciv01,C,21,LAC,26,25,20.2,3.8,7.2,...,7.7,1.5,0.4,0.9,1.4,2.5,9.4,Ivica Zubac,zubaciv01,3

In [47]:
# Filter Dataframe for Frequency = 1 
player_stats_clean_df.loc[(player_stats_clean_df['player_frequency'] == 1)]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,player_name,player_id,player_frequency
0,1,√Ålex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,1.5,0.6,0.5,0.2,0.5,1.7,5.3,√Ålex Abrines,abrinal01,1
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,2.5,0.8,0.1,0.4,0.4,2.4,1.7,Quincy Acy,acyqu01,1
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,1.8,1.9,0.4,0.1,0.8,1.3,3.2,Jaylen Adams,adamsja01,1
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,9.5,1.6,1.5,1.0,1.7,2.6,13.9,Steven Adams,adamsst01,1
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,7.3,2.2,0.9,0.8,1.5,2.5,8.9,Bam Adebayo,adebaba01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,524,Nick Young\youngni01,SG,33,DEN,4,0,9.3,0.8,2.3,...,0.3,0.5,0.0,0.3,0.5,1.0,2.3,Nick Young,youngni01,1
698,525,Thaddeus Young\youngth01,PF,30,IND,81,81,30.7,5.5,10.4,...,6.5,2.5,1.5,0.4,1.5,2.4,12.6,Thaddeus Young,youngth01,1
699,526,Trae Young\youngtr01,PG,20,ATL,81,81,30.9,6.5,15.5,...,3.7,8.1,0.9,0.2,3.8,1.7,19.1,Trae Young,youngtr01,1
700,527,Cody Zeller\zelleco01,C,26,CHO,49,47,25.4,3.9,7.0,...,6.8,2.1,0.8,0.8,1.3,3.3,10.1,Cody Zeller,zelleco01,1
704,529,Ante ≈Ωi≈æiƒá\zizican01,C,22,CLE,59,25,18.3,3.1,5.6,...,5.4,0.9,0.2,0.4,1.0,1.9,7.8,Ante ≈Ωi≈æiƒá,zizican01,1

In [48]:
# Filter for Frequency !=1. When this  count is added up to frequency =1, total should match the total number of rows
player_stats_clean_df.loc[(player_stats_clean_df['player_frequency'] != 1)]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,player_name,player_id,player_frequency
15,16,Ryan Anderson\anderry01,PF,30,TOT,25,8,12.9,0.8,2.8,...,2.2,0.8,0.2,0.0,0.6,1.0,2.5,Ryan Anderson,anderry01,3
16,16,Ryan Anderson\anderry01,PF,30,PHO,15,8,18.5,1.3,4.0,...,3.0,1.1,0.2,0.1,0.8,1.5,3.7,Ryan Anderson,anderry01,3
17,16,Ryan Anderson\anderry01,PF,30,MIA,10,0,4.4,0.2,0.9,...,0.9,0.2,0.1,0.0,0.2,0.2,0.7,Ryan Anderson,anderry01,3
24,23,Trevor Ariza\arizatr01,SF,33,TOT,69,69,34.0,4.3,10.7,...,5.4,3.7,1.3,0.3,1.5,1.9,12.5,Trevor Ariza,arizatr01,3
25,23,Trevor Ariza\arizatr01,SF,33,PHO,26,26,34.0,3.3,8.7,...,5.6,3.3,1.5,0.3,1.5,1.7,9.9,Trevor Ariza,arizatr01,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,528,Tyler Zeller\zellety01,C,29,ATL,2,0,5.5,0.0,1.0,...,3.0,0.5,0.0,0.0,0.0,2.0,0.0,Tyler Zeller,zellety01,3
703,528,Tyler Zeller\zellety01,C,29,MEM,4,1,20.5,4.0,7.0,...,4.5,0.8,0.3,0.8,1.0,4.0,11.5,Tyler Zeller,zellety01,3
705,530,Ivica Zubac\zubaciv01,C,21,TOT,59,37,17.6,3.6,6.4,...,6.1,1.1,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,zubaciv01,3
706,530,Ivica Zubac\zubaciv01,C,21,LAL,33,12,15.6,3.4,5.8,...,4.9,0.8,0.1,0.8,1.0,2.2,8.5,Ivica Zubac,zubaciv01,3
707,530,Ivica Zubac\zubaciv01,C,21,LAC,26,25,20.2,3.8,7.2,...,7.7,1.5,0.4,0.9,1.4,2.5,9.4,Ivica Zubac,zubaciv01,3

In [49]:
# Filter Dataframe for Tm == "TOT and it should match with players who are traded (86)
player_stats_clean_df.loc[(player_stats_clean_df['Tm'] == "TOT")]
# count 86 matches. So, out filter is correct

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,player_name,player_id,player_frequency
15,16,Ryan Anderson\anderry01,PF,30,TOT,25,8,12.9,0.8,2.8,...,2.2,0.8,0.2,0.0,0.6,1.0,2.5,Ryan Anderson,anderry01,3
24,23,Trevor Ariza\arizatr01,SF,33,TOT,69,69,34.0,4.3,10.7,...,5.4,3.7,1.3,0.3,1.5,1.9,12.5,Trevor Ariza,arizatr01,3
31,28,Ron Baker\bakerro01,SG,25,TOT,15,0,10.1,0.3,1.3,...,0.7,1.0,0.4,0.1,0.3,1.2,0.9,Ron Baker,bakerro01,3
38,33,Harrison Barnes\barneha02,PF-SF,26,TOT,77,77,32.9,5.6,13.3,...,4.7,1.5,0.6,0.2,1.3,1.6,16.4,Harrison Barnes,barneha02,3
70,63,Avery Bradley\bradlav01,SG,28,TOT,63,63,30.2,3.9,9.7,...,2.8,2.4,0.7,0.3,1.4,2.7,9.9,Avery Bradley,bradlav01,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,488,Jonas Valanƒçi≈´nas\valanjo01,C,26,TOT,49,27,22.3,6.1,11.0,...,8.6,1.4,0.4,1.1,1.8,3.0,15.6,Jonas Valanƒçi≈´nas,valanjo01,3
690,521,Christian Wood\woodch01,PF,23,TOT,21,2,12.0,2.9,5.6,...,4.0,0.4,0.3,0.5,0.8,0.8,8.2,Christian Wood,woodch01,3
693,522,Delon Wright\wrighde01,PG,26,TOT,75,13,22.7,3.2,7.4,...,3.5,3.3,1.2,0.4,1.0,1.4,8.7,Delon Wright,wrighde01,3
701,528,Tyler Zeller\zellety01,C,29,TOT,6,1,15.5,2.7,5.0,...,4.0,0.7,0.2,0.5,0.7,3.3,7.7,Tyler Zeller,zellety01,3
705,530,Ivica Zubac\zubaciv01,C,21,TOT,59,37,17.6,3.6,6.4,...,6.1,1.1,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,zubaciv01,3

In [50]:
# Filter Dataframe for Frequency !=1 && Tm == "TOT"
#Total number of unique rows would be (frequency ==1) + (frequency !=1 & Tm = "TOT)")
#444 + 86 = 530
player_stats_filtered_df = player_stats_clean_df.loc[(player_stats_clean_df['player_frequency'] == 1) | (player_stats_clean_df['Tm'] == "TOT")]
player_stats_filtered_df
#Row count is 530 and it matches with what is expected

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,player_name,player_id,player_frequency
0,1,√Ålex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,1.5,0.6,0.5,0.2,0.5,1.7,5.3,√Ålex Abrines,abrinal01,1
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,2.5,0.8,0.1,0.4,0.4,2.4,1.7,Quincy Acy,acyqu01,1
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,1.8,1.9,0.4,0.1,0.8,1.3,3.2,Jaylen Adams,adamsja01,1
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,9.5,1.6,1.5,1.0,1.7,2.6,13.9,Steven Adams,adamsst01,1
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,7.3,2.2,0.9,0.8,1.5,2.5,8.9,Bam Adebayo,adebaba01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,526,Trae Young\youngtr01,PG,20,ATL,81,81,30.9,6.5,15.5,...,3.7,8.1,0.9,0.2,3.8,1.7,19.1,Trae Young,youngtr01,1
700,527,Cody Zeller\zelleco01,C,26,CHO,49,47,25.4,3.9,7.0,...,6.8,2.1,0.8,0.8,1.3,3.3,10.1,Cody Zeller,zelleco01,1
701,528,Tyler Zeller\zellety01,C,29,TOT,6,1,15.5,2.7,5.0,...,4.0,0.7,0.2,0.5,0.7,3.3,7.7,Tyler Zeller,zellety01,3
704,529,Ante ≈Ωi≈æiƒá\zizican01,C,22,CLE,59,25,18.3,3.1,5.6,...,5.4,0.9,0.2,0.4,1.0,1.9,7.8,Ante ≈Ωi≈æiƒá,zizican01,1
705,530,Ivica Zubac\zubaciv01,C,21,TOT,59,37,17.6,3.6,6.4,...,6.1,1.1,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,zubaciv01,3

In [51]:
##############################################################################
# The following section add additional columns needed 
# playing_season if value is 2018, then it maeans that the season is 2018-19
##############################################################################
player_stats_filtered_df['playing_season'] = "2018"
player_stats_filtered_df

/Users/dhanaprakashdurairaj/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,player_name,player_id,player_frequency,playing_season
0,1,√Ålex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,0.6,0.5,0.2,0.5,1.7,5.3,√Ålex Abrines,abrinal01,1,2018
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,0.8,0.1,0.4,0.4,2.4,1.7,Quincy Acy,acyqu01,1,2018
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,1.9,0.4,0.1,0.8,1.3,3.2,Jaylen Adams,adamsja01,1,2018
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,1.6,1.5,1.0,1.7,2.6,13.9,Steven Adams,adamsst01,1,2018
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,2.2,0.9,0.8,1.5,2.5,8.9,Bam Adebayo,adebaba01,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,526,Trae Young\youngtr01,PG,20,ATL,81,81,30.9,6.5,15.5,...,8.1,0.9,0.2,3.8,1.7,19.1,Trae Young,youngtr01,1,2018
700,527,Cody Zeller\zelleco01,C,26,CHO,49,47,25.4,3.9,7.0,...,2.1,0.8,0.8,1.3,3.3,10.1,Cody Zeller,zelleco01,1,2018
701,528,Tyler Zeller\zellety01,C,29,TOT,6,1,15.5,2.7,5.0,...,0.7,0.2,0.5,0.7,3.3,7.7,Tyler Zeller,zellety01,3,2018
704,529,Ante ≈Ωi≈æiƒá\zizican01,C,22,CLE,59,25,18.3,3.1,5.6,...,0.9,0.2,0.4,1.0,1.9,7.8,Ante ≈Ωi≈æiƒá,zizican01,1,2018
705,530,Ivica Zubac\zubaciv01,C,21,TOT,59,37,17.6,3.6,6.4,...,1.1,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,zubaciv01,3,2018

In [52]:
#############################################################################
# The following section creates a new data frame with just required columns 
# and rename them
############################################################################

In [53]:
# List column names 
player_stats_filtered_df.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'player_name', 'player_id', 'player_frequency', 'playing_season'],
      dtype='object')

In [54]:
# Create New DataFRame with only the columns that is needed
player_stats_cleaned_df = player_stats_filtered_df[['player_id','playing_season','Pos','Age','Tm','G','MP','FG','FG%','3P','3P%','eFG%','FT','FT%','TRB','AST','STL','BLK','TOV','PTS']]
player_stats_cleaned_df

,player_id,playing_season,Pos,Age,Tm,G,MP,FG,FG%,3P,3P%,eFG%,FT,FT%,TRB,AST,STL,BLK,TOV,PTS
0,abrinal01,2018,SG,25,OKC,31,19.0,1.8,0.357,1.3,0.323,0.487,0.4,0.923,1.5,0.6,0.5,0.2,0.5,5.3
1,acyqu01,2018,PF,28,PHO,10,12.3,0.4,0.222,0.2,0.133,0.278,0.7,0.700,2.5,0.8,0.1,0.4,0.4,1.7
2,adamsja01,2018,PG,22,ATL,34,12.6,1.1,0.345,0.7,0.338,0.459,0.2,0.778,1.8,1.9,0.4,0.1,0.8,3.2
3,adamsst01,2018,C,25,OKC,80,33.4,6.0,0.595,0.0,0.000,0.595,1.8,0.500,9.5,1.6,1.5,1.0,1.7,13.9
4,adebaba01,2018,C,21,MIA,82,23.3,3.4,0.576,0.0,0.200,0.579,2.0,0.735,7.3,2.2,0.9,0.8,1.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,youngtr01,2018,PG,20,ATL,81,30.9,6.5,0.418,1.9,0.324,0.480,4.2,0.829,3.7,8.1,0.9,0.2,3.8,19.1
700,zelleco01,2018,C,26,CHO,49,25.4,3.9,0.551,0.1,0.273,0.559,2.3,0.787,6.8,2.1,0.8,0.8,1.3,10.1
701,zellety01,2018,C,29,TOT,6,15.5,2.7,0.533,0.0,0.000,0.533,2.3,0.778,4.0,0.7,0.2,0.5,0.7,7.7
704,zizican01,2018,C,22,CLE,59,18.3,3.1,0.553,0.0,0.000,0.553,1.6,0.705,5.4,0.9,0.2,0.4,1.0,7.8
705,zubaciv01,2018,C,21,TOT,59,17.6,3.6,0.559,0.0,0.000,0.559,1.7,0.802,6.1,1.1,0.2,0.9,1.2,8.9

In [55]:
# Rename Column Names to match the one with the Database
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"Pos":"playing_position"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"Age":"playing_age"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"Tm":"team_name"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"G":"no_of_games_played"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"MP":"no_minutes_played"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"FG":"field_goals_made"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"FG%":"field_goals_pctg"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"3P":"three_pointers_made"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"3P%":"three_point_pctg"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"eFG%":"effective_field_goal_pctg"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"FT":"free_thows_made"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"FT%":"free_throws_pctg"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"TRB":"total_rebounds"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"AST":"no_of_assists"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"STL":"no_of_steals"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"BLK":"no_of_blocks"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"TOV":"no_of_turnovers"})
player_stats_cleaned_df = player_stats_cleaned_df.rename(columns={"PTS":"points"})
player_stats_cleaned_df

,player_id,playing_season,playing_position,playing_age,team_name,no_of_games_played,no_minutes_played,field_goals_made,field_goals_pctg,three_pointers_made,three_point_pctg,effective_field_goal_pctg,free_thows_made,free_throws_pctg,total_rebounds,no_of_assists,no_of_steals,no_of_blocks,no_of_turnovers,points
0,abrinal01,2018,SG,25,OKC,31,19.0,1.8,0.357,1.3,0.323,0.487,0.4,0.923,1.5,0.6,0.5,0.2,0.5,5.3
1,acyqu01,2018,PF,28,PHO,10,12.3,0.4,0.222,0.2,0.133,0.278,0.7,0.700,2.5,0.8,0.1,0.4,0.4,1.7
2,adamsja01,2018,PG,22,ATL,34,12.6,1.1,0.345,0.7,0.338,0.459,0.2,0.778,1.8,1.9,0.4,0.1,0.8,3.2
3,adamsst01,2018,C,25,OKC,80,33.4,6.0,0.595,0.0,0.000,0.595,1.8,0.500,9.5,1.6,1.5,1.0,1.7,13.9
4,adebaba01,2018,C,21,MIA,82,23.3,3.4,0.576,0.0,0.200,0.579,2.0,0.735,7.3,2.2,0.9,0.8,1.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,youngtr01,2018,PG,20,ATL,81,30.9,6.5,0.418,1.9,0.324,0.480,4.2,0.829,3.7,8.1,0.9,0.2,3.8,19.1
700,zelleco01,2018,C,26,CHO,49,25.4,3.9,0.551,0.1,0.273,0.559,2.3,0.787,6.8,2.1,0.8,0.8,1.3,10.1
701,zellety01,2018,C,29,TOT,6,15.5,2.7,0.533,0.0,0.000,0.533,2.3,0.778,4.0,0.7,0.2,0.5,0.7,7.7
704,zizican01,2018,C,22,CLE,59,18.3,3.1,0.553,0.0,0.000,0.553,1.6,0.705,5.4,0.9,0.2,0.4,1.0,7.8
705,zubaciv01,2018,C,21,TOT,59,17.6,3.6,0.559,0.0,0.000,0.559,1.7,0.802,6.1,1.1,0.2,0.9,1.2,8.9

In [56]:
#####################
# Write to CSV File
#####################

In [57]:
# writing Clean data to csv file
player_stats_cleaned_df.to_csv(r'../../Resources/PreprocessedDataFiles/NBA Players Stats 201819_clean.csv', encoding='utf-8', header='true')